### ISSUE TITLE
State updates props but willreceiveprops doesn't seem to call

### ISSUE THREAD

**Issue by chinds185a** [Julusian/react-bootstrap-switch#6]
When changing the state of the switch, the props change from true to false but the switches state does not.

getInitialState: function() {

```
    return {
        buttonState    : false,
        breakingNewsOn : false,
        headlineOn     : false,
        sublineOn      : false,
        infoStrapOn    : false,
        storyTypeValue : null
    };
},
```

takeCG: function (event, callback) {

```
    console.log("The info strap was: " + this.state.infoStrapOn)

    this.setState({
        infoStrapOn : !this.state.infoStrapOn,
        headlineOn  : !this.state.headlineOn,
        sublineOn   : !this.state.sublineOn,
    });

},
```

switch does not change when takeCG is called and its state is updated
<Switch 
                                id          = "story-strap-headline-toggle" 
                                value       = {'some string or integer value'} 
                                state       = {this.state.headlineOn}
                                size        = {'mini'}
                                lableWoidth = {2} 
                                onColor     = {'danger'}  
                            />

**Comment by penguinpowernz** [comment]
Yea.  If you look at the readme it says **These should be defined on the JSX node, many cannot be changed once they have been set without recreating the node.**.  I just found this after debugging my code for a while.  Unfortunately it makes it pretty useless as a ReactJS component because that is how React get updates through to the component.

With the vanilla library I guess you use something like `$('#switch').value(false)` to change it but I don't know how to call a method on a React component.

I want to do a pull request but the code is coffeejs vomit.

**Comment by penguinpowernz** [comment]
Pretty simple fix actually :)

**Comment by chris-hinds** [comment]
Glad you found a fix. Unfortunately I have moved on to another library. As the components read only prop seemed to completely disable the switch. 

Hopefully this will better for someone else now though.

**Comment by Julusian** [comment]
I believe this should be resolved now, feel free to reopen or create another ticket if it is not

**Comment by penguinpowernz** [comment]
Sweet!
